# Generated by Django 5.1.5 on 2025-07-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_a_family_alter_family_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='joining_id',
            field=models.CharField(max_length=6),
        ),
    ]
