# Generated by Django 5.1.5 on 2025-07-07 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_family_joining_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='the_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.family'),
        ),
    ]
